[tool.black]
line_length = 120

[tool.flake8]
max-line-length = 120
select = "F,E,W,B,B901,B902,B903"
exclude = [
    ".eggs",
    ".git",
    ".tox",
    "nssm",
    "obj",
    "out",
    "packages",
    "pywin32",
    "tests",
    "swagger_client"
]
ignore = [
    "E722",
    "B001",
    "W503",
    "E203",
    "E402"
]

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true

[tool.pylint.'MESSAGES CONTROL']
disable= [
    "duplicate-code",
    "import-outside-toplevel",
    "unspecified-encoding"
]
