[tool.black]
line_length = 88

[tool.flake8]
max-line-length = 99
select = "F,E,W,B,B901,B902,B903"
exclude = [
    ".eggs",
    ".git",
    ".tox",
    "nssm",
    "obj",
    "out",
    "packages",
    "pywin32",
    "tests",
    "swagger_client"
]
ignore = [
    "E722",
    "B001",
    "W503",
    "E203",
    "E402"
]

[tool.isort]
multi_line_output = 3
line_length = 99
include_trailing_comma = true

[tool.pylint.'FORMAT']
max-line-length=99

[tool.pylint.'MESSAGES CONTROL']
disable= [
    "bare-except",
    "broad-except",
    "consider-using-with",
    "consider-using-generator",
    "duplicate-code",
    "import-outside-toplevel",
    "invalid-name",
    "import-error",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "unspecified-encoding",
    "wrong-import-position",
]

[tool.pyright]
reportOptionalMemberAccess = false
reportGeneralTypeIssues = false
reportOptionalSubscript = false
reportUnboundVariable = false
